from __future__ import annotations

from pathlib import Path

from .io import append_jsonl
from .models import Message, Party, WorkflowDefinition, WorkflowStep, new_id, utc_now_iso


class MessageBus:
    def __init__(self, root: Path, workflow_run_id: str) -> None:
        self.root = root
        self.workflow_run_id = workflow_run_id
        self.log_path = root / "logs" / "runs" / workflow_run_id / "messages.jsonl"

    def create_for_step(
        self,
        workflow: WorkflowDefinition,
        step: WorkflowStep,
        sender: Party,
        receiver: Party,
        context: dict[str, object],
    ) -> Message:
        instructions = step.instructions or f"Perform workflow step {step.id}."
        message = Message(
            id=new_id("msg"),
            timestamp=utc_now_iso(),
            workflow_id=workflow.id,
            sender=sender,
            receiver=receiver,
            task={
                "objective": workflow.purpose,
                "instructions": instructions,
                "expected_output": step.output,
                "quality_criteria": workflow.validation,
                "constraints": [],
            },
            context=context,
            assumptions=[],
            reasoning_summary="Message generated by Kernel v0.1 from workflow definition.",
            evidence=[],
            confidence="unknown",
            requested_action=step.type,
            status="sent",
        )
        self.persist(message)
        return message

    def persist(self, message: Message) -> None:
        append_jsonl(self.log_path, {**message.to_dict(), "workflow_run_id": self.workflow_run_id})
